import React from 'react'
import Script from 'next/script'
const contect = () => {
  return (
    <div>
      contect
      <Script>
        alert("welcome contact page")
      </Script>
    </div>
    
  )
}

export default contect

export const metadata = {
  title: "Create Next App contact",
  description: "contact Generated by create next app",
};