import { Inter } from "next/font/google";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " admin Create Next App",
  description: " admin Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
   <>
   <span> admin layout</span>
   {children}
   </>
      
  );
}