import React from 'react'
import Image from 'next/image'
const about = () => {
  return (
    <div>
     <Image src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLQUQ6g6NjGqj3qncgsJGpxzzRrL_qDAc1qQ&s"  alt="" width={100} height={100}/>
    </div>
  )
}

export default about

export const metadata = {
  title: "Create Next App about",
  description: "Generated by create next app about",
};